# Generated by Django 4.0.3 on 2022-03-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_image_title_image_sketch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='sketch',
        ),
    ]
