# Generated by Django 4.0.3 on 2022-03-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_image_sketch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_img', models.ImageField(null=True, upload_to='original/')),
                ('original_size', models.TextField(null=True)),
                ('quality', models.CharField(max_length=3, null=True)),
                ('converted_img', models.ImageField(null=True, upload_to='converted/')),
                ('converted_size', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
