# Generated by Django 4.0.3 on 2022-03-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_images_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='converted_size',
        ),
        migrations.RemoveField(
            model_name='images',
            name='original_size',
        ),
        migrations.RemoveField(
            model_name='images',
            name='quality',
        ),
    ]
